spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

# ======================================================================================================================
# Custom Property
# ======================================================================================================================

